name: Build RapBind 0.3.DL
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install MinGW
        run: sudo apt update && sudo apt install -y mingw-w64
      - name: Build
        run: |
          mkdir -p build
          i686-w64-mingw32-g++ -shared -O2 -mwindows -o build/RapBind.asi src/*.cpp -static-libgcc -static-libstdc++
      - uses: actions/upload-artifact@v4
        with:
          name: RapBind-0.3DL
          path: build/RapBind.asi
